# Generated by Django 3.0.1 on 2020-07-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=11, unique=True, verbose_name='username'),
        ),
    ]
