# Generated by Django 3.0.1 on 2020-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0003_auto_20200713_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matric_number',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
