# Generated by Django 3.0.1 on 2020-07-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0005_auto_20200713_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='number_of_vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
