# Generated by Django 3.0.1 on 2020-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0007_auto_20200715_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='passport'),
        ),
    ]
