# Generated by Django 3.0.1 on 2020-07-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0008_auto_20200715_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
